---
- name: "Generate template from sample dotenv file"
  parse_dotenv_sample: dotenv_sample_path="{{ dotenv_sample }}"
  register: gen_template

- name: "Create local temporary directory"
  tempfile: state=directory suffix=dotenv_tmpl
  register: local_tmpdir
  delegate_to: localhost
  become: false

- name: "Fetch generated template"
  fetch:
    src: "{{ gen_template.dotenv_template_path }}"
    dest: "{{ local_tmpdir.path }}/env"
    flat: yes
  register: local_template

- name: "Copy filled template back to the server"
  template:
    src: "{{ local_template.dest }}"
    dest: "{{ dest }}"
    mode: "{{ dest_mode }}"
    owner: "{{ dest_owner }}"
    group: "{{ dest_group }}"

- name: clean up local temporary file
  file: name={{ local_template.dest }} state=absent
  delegate_to: localhost
  become: false

- name: clean up remote temporary file
  file: name={{ gen_template.dotenv_template_path }} state=absent
