---
- name: Converge
  hosts: all
  pre_tasks:
    - name: copy test files
      copy: src={{ item.file }} dest=/tmp/{{ item.file | basename() }}
      with_items: "{{ test_files }}"
    - name: load substitution variables
      include_vars: file={{ item.var_file }} name={{ item.var }}
      with_items: "{{ test_files }}"

  tasks:
    - name: invoke the dotenv-generator role
      include_role:
        name: ansible-dotenv-generator
      vars:
        dotenv_sample: /tmp/{{ item.file | basename() }}
        env: "{{ vars[item.var] }}"
        dest: "{{ item.dest }}"
      with_items: "{{ test_files }}"
